services:
  api:
    build:
      context: .
      target: api
    environment:
      Cors__Origins__0: http://localhost:5210
    ports:
      - "5184:8080"

  app:
    build:
      context: .
      target: app
    ports:
      - "5210:80"
    depends_on:
      - api
